apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmitriyf7498-kubesingleapp-deployment-dev
  labels:
    app: dmitriyf7498-kubesingleapp-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dmitriyf7498-kubesingleapp-dev
  template:
    metadata:
      labels:
        app: dmitriyf7498-kubesingleapp-dev
    spec:
      containers:
        - name: dmitriyf7498-kubesingleapp-dev
          image: dmitriyf7498/kube-single-app:dev
          imagePullPolicy: Always # ВСЕГДА скачивать образ (важно для тега :dev)
