apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmitriyf7498-kubesingleapp-deployment-prod
  labels:
    app: dmitriyf7498-kubesingleapp-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dmitriyf7498-kubesingleapp-prod
  template:
    metadata:
      labels:
        app: dmitriyf7498-kubesingleapp-prod
    spec:
      containers:
        - name: dmitriyf7498-kubesingleapp-prod
          image: dmitriyf7498/kube-single-app:latest
          imagePullPolicy: Always # ВСЕГДА скачивать образ (важно для тега :dev)