apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesingleapp-deployment
  labels:
    app: kubesingleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesingleapp
  template:
    metadata:
      labels:
        app: kubesingleapp
    spec:
      containers:
        - name: kubesingleapp
          image: dmitriyf7498/kube-single-app-vol:latest
          volumeMounts:
            - mountPath: /app/storage
              name: kubesingleapp-volume
          imagePullPolicy: Always # ВСЕГДА скачивать образ (важно для тега :dev)
          ports:
            - containerPort: 8092 # Порт, который слушает приложение внутри
      volumes:
        - name: kubesingleapp-volume
          persistentVolumeClaim:
            claimName: local-persistent-volume-claim
